export type CountryType =
  | 'all'
  | 'korea'
  | 'pizza'
  | 'china'
  | 'japan'
  | 'asia'
  | 'mexico'
  | 'italy'
  | 'france';

export type MenuItem = {
  menu: string;
  image: string;
  tags?: string[];
};

export type MenuMap = Record<CountryType, MenuItem[]>;

const IMG = '/img/ahoxy/menu';

const korea: MenuItem[] = [
  { menu: "김밥 꼬마김밥 충무김밥 참치김밥 유부김밥 불고기김밥 제육김밥", image: `${IMG}/gimbap.webp`, tags: ["점심", "저녁", "혼밥", "회식"] },
  { menu: "라면 치즈라면 떡라면 참치라면 콩나물라면", image: `${IMG}/ramyun.webp`, tags: ["해장", "저녁", "혼밥", "면"] },
  { menu: "떡볶이 엽기떡볶이", image: `${IMG}/tteokbokki.webp`, tags: ["점심", "저녁", "분식", "매움"] },
  { menu: "순대 찹쌀순대 오징어순대", image: `${IMG}/sundae.webp`, tags: ["점심", "저녁", "분식", "야식"] },
  { menu: "족발", image: `${IMG}/jokbal.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "어묵탕 어묵볶음", image: `${IMG}/eomuk.webp`, tags: ["점심", "저녁", "겨울", "국물"] },
  { menu: "떡갈비", image: `${IMG}/ddgb.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "골뱅이무침", image: `${IMG}/golbaengi-muchim.webp`, tags: ["점심", "저녁", "야식"] },
  { menu: "순두부찌개 바지락순두부찌개", image: `${IMG}/sdbjg.webp`, tags: ["점심", "저녁", "봄", "국물"] },
  { menu: "아구찜", image: `${IMG}/agujjim.webp`, tags: ["점심", "저녁", "매움", "든든함"] },
  { menu: "부대찌개", image: `${IMG}/bdjg.webp`, tags: ["점심", "저녁", "회식", "국물", "든든함"] },
  { menu: "대게찜", image: `${IMG}/dgj.webp`, tags: ["점심", "저녁", "가을", "든든함"] },
  { menu: "갈비탕", image: `${IMG}/galbitang.webp`, tags: ["점심", "저녁", "회식", "겨울"] },
  { menu: "감자탕", image: `${IMG}/gamjatang.webp`, tags: ["해장", "저녁", "국물", "든든함"] },
  { menu: "낙지볶음 낙지덮밥 낙곱새", image: `${IMG}/ngs.webp`, tags: ["점심", "저녁", "매움", "든든함"] },
  { menu: "닭볶음탕", image: `${IMG}/ddrt.webp`, tags: ["점심", "저녁", "국물", "매움"] },
  { menu: "묵은지 돼지김치찜", image: `${IMG}/djkcj.webp`, tags: ["점심", "저녁", "든든함"] },
  { menu: "찜닭 안동찜닭", image: `${IMG}/jjimdak.webp`, tags: ["점심", "저녁", "고기", "든든함"] },
  { menu: "해장국 시래기해장국 뼈해장국", image: `${IMG}/bhjg.webp`, tags: ["해장", "저녁", "국물"] },
  { menu: "회 참치회 포항물회 회덮밥", image: `${IMG}/hoe.webp`, tags: ["점심", "저녁", "여름", "가벼움"] },
  { menu: "물회 포항물회 회국수", image: `${IMG}/converted_포항물회.webp`, tags: ["점심", "저녁", "여름", "국물"] },
  { menu: "비빔국수 쫄면 열무비빔국수", image: `${IMG}/bibim.webp`, tags: ["점심", "여름", "면", "매움"] },
  { menu: "칼국수 들깨칼국수 닭칼국수 매생이굴칼국수", image: `${IMG}/kgs.webp`, tags: ["점심", "저녁", "겨울", "국물"] },
  { menu: "수제비 들깨수제비 김치수제비", image: `${IMG}/sjb.webp`, tags: ["점심", "저녁", "겨울", "국물"] },
  { menu: "물냉면 평양냉면 밀면", image: `${IMG}/mul-naengmyeon.webp`, tags: ["점심", "저녁", "여름", "면"] },
  { menu: "비빔냉면 열무냉면 회냉면", image: `${IMG}/bibim-naengmyeon.webp`, tags: ["점심", "저녁", "여름", "면"] },
  { menu: "육쌈냉면 숯불고기냉면", image: `${IMG}/bibim-naengmyeon.webp`, tags: ["점심", "저녁", "회식", "여름"] },
  { menu: "만둣국", image: `${IMG}/mandu-guk.webp`, tags: ["점심", "저녁", "겨울", "국물"] },
  { menu: "육개장 버섯육개장 소고기육개장", image: `${IMG}/ygj.webp`, tags: ["점심", "저녁", "가을", "매움"] },
  { menu: "된장찌개 차돌박이된장찌개 청국장", image: `${IMG}/djjg.webp`, tags: ["점심", "저녁", "국물", "든든함"] },
  { menu: "김치찌개 꽁치김치찌개 돼지고기김치찌개", image: `${IMG}/kcjg.webp`, tags: ["점심", "저녁", "국물", "매움"] },
  { menu: "매운탕 광어매운탕 꽃게매운탕", image: `${IMG}/mt.webp`, tags: ["점심", "저녁", "가을", "국물"] },
  { menu: "순대국밥 돼지국밥", image: `${IMG}/sundae-gukbap.webp`, tags: ["점심", "저녁", "국물", "분식"] },
  { menu: "설렁탕", image: `${IMG}/slt.webp`, tags: ["점심", "저녁", "겨울", "국물"] },
  { menu: "알밥", image: `${IMG}/al-bap.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "파전 감자전 해물전", image: `${IMG}/pajeon.webp`, tags: ["점심", "저녁", "봄"] },
  { menu: "전복죽 호박죽 소고기죽 해물죽", image: `${IMG}/juk.webp`, tags: ["아침", "점심", "가벼움"] },
  { menu: "삼계탕 닭한마리", image: `${IMG}/samgyetang.webp`, tags: ["점심", "저녁", "여름", "국물", "든든함"] },
  { menu: "콩나물국밥 콩나물비빔밥", image: `${IMG}/knm.webp`, tags: ["해장", "저녁", "국물", "든든함"] },
  { menu: "장어구이 장어덮밥", image: `${IMG}/jang-eo-gui.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "꽃게탕", image: `${IMG}/ggt.webp`, tags: ["점심", "저녁", "가을", "국물"] },
  { menu: "잔치국수", image: `${IMG}/jcgs.webp`, tags: ["점심", "저녁", "혼밥", "국물"] },
  { menu: "육회 육회비빔밥", image: `${IMG}/yookhoe.webp`, tags: ["점심", "저녁", "가벼움", "든든함"] },
  { menu: "삼겹살 오겹살 갈매기살 항정살", image: `${IMG}/samgyeopsal.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "제육볶음 제육쌈밥 제육덮밥", image: `${IMG}/jeyook.jfif`, tags: ["점심", "저녁", "매움", "고기"] },
  { menu: "닭갈비 불닭 치즈닭갈비", image: `${IMG}/dgb.webp`, tags: ["점심", "저녁", "회식", "매움"] },
  { menu: "닭꼬치", image: `${IMG}/dkch.webp`, tags: ["점심", "저녁", "분식", "고기"] },
  { menu: "훈제오리 오리주물럭", image: `${IMG}/hjori.webp`, tags: ["점심", "저녁", "고기"] },
  { menu: "갈비찜 LA갈비찜", image: `${IMG}/galbijjim.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "숯불갈비 LA갈비 등갈비", image: `${IMG}/sutbul-galbi.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "쪽갈비 매운쪽갈비 등갈비구이", image: `${IMG}/sutbul-galbi.webp`, tags: ["점심", "저녁", "회식", "매움"] },
  { menu: "뚝배기 불고기", image: `${IMG}/ddb.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "꼬막 꼬막비빔밥", image: `${IMG}/kkm.webp`, tags: ["점심", "저녁", "가을", "든든함"] },
  { menu: "간장게장 양념게장 게장정식", image: `${IMG}/converted_여수돌게장.webp`, tags: ["점심", "저녁", "가을", "매움"] },
  { menu: "돼지고기 수육 보쌈", image: `${IMG}/suyook.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "홍합탕", image: `${IMG}/honghab.webp`, tags: ["점심", "저녁", "겨울", "국물"] },
  { menu: "떡국", image: `${IMG}/tgtg.webp`, tags: ["점심", "저녁", "겨울", "국물"] },
  { menu: "폭탄 계란찜", image: `${IMG}/grj.webp`, tags: ["점심", "저녁", "든든함"] },
  { menu: "곰탕 나주곰탕 꼬리곰탕", image: `${IMG}/gomtang.webp`, tags: ["점심", "저녁", "겨울", "국물"] },
  { menu: "호떡", image: `${IMG}/hott.webp`, tags: ["점심", "저녁", "겨울", "분식"] },
  { menu: "잡채", image: `${IMG}/japchae.webp`, tags: ["점심", "저녁"] },
  { menu: "미역국", image: `${IMG}/myg.webp`, tags: ["아침", "저녁", "국물"] },
  { menu: "콩국수", image: `${IMG}/cgscgs.webp`, tags: ["점심", "여름", "면", "가벼움"] },
  { menu: "메밀국수 막국수 들기름막국수", image: `${IMG}/mmgs.webp`, tags: ["점심", "여름", "면", "가벼움"] },
  { menu: "산낙지", image: `${IMG}/sannak.webp`, tags: ["점심", "저녁", "매움"] },
  { menu: "조개구이 가리비구이", image: `${IMG}/jgjgjg.webp`, tags: ["점심", "저녁", "회식"] },
  { menu: "고등어구이 삼치구이", image: `${IMG}/mackeee.webp`, tags: ["점심", "저녁"] },
  { menu: "감자조림 알감자조림", image: `${IMG}/gamjajorim.webp`, tags: ["점심", "저녁", "봄"] },
  { menu: "소고기무국 무국", image: `${IMG}/moot.webp`, tags: ["점심", "저녁", "국물"] },
  { menu: "곱창 곱창전골", image: `${IMG}/gobchang.webp`, tags: ["점심", "저녁", "회식", "국물"] },
  { menu: "두부조림", image: `${IMG}/dbjr.webp`, tags: ["점심", "저녁", "봄", "다이어트"] },
  { menu: "두루치기 돼지두루치기", image: `${IMG}/duru.webp`, tags: ["점심", "저녁", "매움"] },
  { menu: "알탕", image: `${IMG}/altang.webp`, tags: ["점심", "저녁", "가을", "국물"] },
  { menu: "추어탕", image: `${IMG}/choot.webp`, tags: ["점심", "저녁", "가을", "국물"] },
  { menu: "닭발 닭똥집", image: `${IMG}/dakbb.webp`, tags: ["점심", "저녁", "회식", "고기", "야식"] },
  { menu: "솥밥 스테이크솥밥", image: `${IMG}/sotbap.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  // Regional specialties
  { menu: "강릉감자옹심이", image: `${IMG}/converted_강릉감자옹심이.webp`, tags: ["점심", "저녁"] },
  { menu: "강릉초당순두부", image: `${IMG}/converted_강릉초당순두부.webp`, tags: ["점심", "저녁", "봄"] },
  { menu: "거제대구탕", image: `${IMG}/converted_거제대구탕.webp`, tags: ["해장", "저녁", "국물", "든든함"] },
  { menu: "고성하모회", image: `${IMG}/converted_고성하모회.webp`, tags: ["점심", "저녁", "가벼움"] },
  { menu: "고창풍천장어구이", image: `${IMG}/converted_고창풍천장어구이.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "광양불고기", image: `${IMG}/converted_광양불고기.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "광주송정떡갈비", image: `${IMG}/converted_광주송정떡갈비.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "광주오리탕", image: `${IMG}/converted_광주오리탕.webp`, tags: ["점심", "저녁", "국물", "고기"] },
  { menu: "나주곰탕", image: `${IMG}/converted_나주곰탕.webp`, tags: ["점심", "저녁", "겨울", "국물"] },
  { menu: "나주영산포홍어", image: `${IMG}/converted_나주영산포홍어.webp`, tags: ["점심", "저녁", "가을"] },
  { menu: "남원추어탕", image: `${IMG}/converted_남원추어탕.webp`, tags: ["점심", "저녁", "가을", "국물"] },
  { menu: "대구납작만두", image: `${IMG}/converted_대구납작만두.webp`, tags: ["점심", "저녁", "분식"] },
  { menu: "대구동인동찜갈비", image: `${IMG}/converted_대구동인동찜갈비.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "대구막창", image: `${IMG}/converted_대구막창.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "목포세발낙지", image: `${IMG}/converted_목포세발낙지.webp`, tags: ["점심", "저녁", "매움"] },
  { menu: "목포홍어삼합", image: `${IMG}/converted_목포홍어삼합.webp`, tags: ["점심", "저녁", "가을"] },
  { menu: "부산돼지국밥", image: `${IMG}/converted_부산돼지국밥.webp`, tags: ["점심", "저녁", "국물", "든든함"] },
  { menu: "부산밀면", image: `${IMG}/converted_부산밀면.webp`, tags: ["점심", "저녁", "여름", "면"] },
  { menu: "순천짱뚱어탕", image: `${IMG}/converted_순천짱뚱어탕.webp`, tags: ["점심", "저녁", "국물", "든든함"] },
  { menu: "안동간고등어정식", image: `${IMG}/converted_안동간고등어정식.webp`, tags: ["점심", "저녁"] },
  { menu: "여수금풍생이구이", image: `${IMG}/converted_여수금풍생이구이.webp`, tags: ["점심", "저녁"] },
  { menu: "여수돌게장", image: `${IMG}/converted_여수돌게장.webp`, tags: ["점심", "저녁", "가을"] },
  { menu: "여수서대회", image: `${IMG}/converted_여수서대회.webp`, tags: ["점심", "저녁", "가벼움"] },
  { menu: "영광법성포굴비정식", image: `${IMG}/converted_영광법성포굴비정식.webp`, tags: ["점심", "저녁", "가을"] },
  { menu: "영덕대게찜", image: `${IMG}/converted_영덕대게찜.webp`, tags: ["점심", "저녁", "가을", "든든함"] },
  { menu: "전주콩나물국밥", image: `${IMG}/converted_전주콩나물국밥.webp`, tags: ["해장", "저녁", "국물", "든든함"] },
  { menu: "진주냉면", image: `${IMG}/converted_진주냉면.webp`, tags: ["점심", "저녁", "여름", "면"] },
  { menu: "진주비빔밥", image: `${IMG}/converted_진주비빔밥.webp`, tags: ["점심", "저녁", "든든함"] },
  { menu: "창원아구찜", image: `${IMG}/converted_창원아구찜.webp`, tags: ["점심", "저녁", "매움", "든든함"] },
  { menu: "춘천닭갈비", image: `${IMG}/converted_춘천닭갈비.webp`, tags: ["점심", "저녁", "회식", "매움"] },
  { menu: "통영충무김밥", image: `${IMG}/converted_통영충무김밥.webp`, tags: ["점심", "저녁", "혼밥", "분식"] },
  { menu: "포항물회", image: `${IMG}/converted_포항물회.webp`, tags: ["점심", "저녁", "여름", "가벼움"] },
  { menu: "보성벌교꼬막정식", image: `${IMG}/converted_보성벌교꼬막정식.webp`, tags: ["점심", "저녁", "가을"] },
  { menu: "장흥삼합", image: `${IMG}/converted_장흥삼합.webp`, tags: ["점심", "저녁"] },
  { menu: "담양창평국밥", image: `${IMG}/converted_담양창평국밥.webp`, tags: ["점심", "저녁", "국물", "든든함"] },
  { menu: "양양섭국", image: `${IMG}/converted_양양섭국.webp`, tags: ["점심", "저녁", "국물"] },
  { menu: "화순순두부", image: `${IMG}/converted_화순순두부.webp`, tags: ["점심", "저녁", "봄"] },
  { menu: "보성양탕", image: `${IMG}/converted_보성양탕.webp`, tags: ["점심", "저녁", "국물", "든든함"] },
  { menu: "비빔밥 돌솥비빔밥", image: `${IMG}/sotbap.webp`, tags: ["점심", "저녁", "든든함"] },
  { menu: "불고기 백반", image: `${IMG}/ddb.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "오징어볶음 오징어덮밥", image: `${IMG}/ngs.webp`, tags: ["점심", "저녁", "매움", "든든함"] },
  { menu: "감자전 메밀전병", image: `${IMG}/pajeon.webp`, tags: ["점심", "저녁", "봄"] },
  { menu: "우렁쌈밥 쌈밥정식", image: `${IMG}/jeyook.jfif`, tags: ["점심", "저녁", "가벼움", "든든함"] },
  { menu: "닭개장", image: `${IMG}/ygj.webp`, tags: ["점심", "저녁", "국물", "매움"] },
  { menu: "북엇국 황태해장국", image: `${IMG}/moot.webp`, tags: ["해장", "저녁", "국물"] },
  { menu: "돌솥알밥", image: `${IMG}/al-bap.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "멸치국수 김치말이국수", image: `${IMG}/jcgs.webp`, tags: ["점심", "저녁", "국물", "면"] },
  { menu: "제주고기국수", image: `${IMG}/kgs.webp`, tags: ["점심", "저녁", "국물", "면", "고기"] },

];

const pizza: MenuItem[] = [
  { menu: "피자 고르곤졸라피자 마르게리타 시카고피자", image: `${IMG}/pizza.webp`, tags: ["점심", "저녁", "회식", "든든함", "야식"] },
  { menu: "치킨", image: `${IMG}/chicken.webp`, tags: ["점심", "저녁", "회식", "고기", "든든함"] },
  { menu: "햄버거", image: `${IMG}/hamburger.webp`, tags: ["점심", "저녁", "고기", "든든함"] },
  { menu: "팬케이크", image: `${IMG}/pancake.webp`, tags: ["아침", "점심", "가벼움"] },
  { menu: "와플", image: `${IMG}/waffle.webp`, tags: ["아침", "점심", "가벼움"] },
  { menu: "샌드위치", image: `${IMG}/sandwich.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "핫도그 명랑핫도그 콘도그", image: `${IMG}/hot-dog.webp`, tags: ["점심", "저녁", "분식", "야식"] },
  { menu: "토스트", image: `${IMG}/toast.webp`, tags: ["아침", "점심", "가벼움"] },
  { menu: "치즈스틱", image: `${IMG}/cheese-sticks.webp`, tags: ["점심", "저녁"] },
  { menu: "붕어빵", image: `${IMG}/bb.webp`, tags: ["점심", "저녁", "겨울", "분식"] },
  { menu: "닭강정", image: `${IMG}/dakgangjeong.webp`, tags: ["점심", "저녁", "고기", "야식"] },
  { menu: "스테이크", image: `${IMG}/steak.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "폭립 Pork Rib", image: `${IMG}/porkrib.webp`, tags: ["점심", "저녁", "고기", "든든함"] },
  { menu: "연어 스테이크", image: `${IMG}/salmonsteak.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "연어 샐러드 훈제연어", image: `${IMG}/salmon.webp`, tags: ["점심", "여름", "다이어트", "가벼움"] },
  { menu: "당근 케이크", image: `${IMG}/carrotcake.webp`, tags: ["점심", "가벼움"] },
  { menu: "오믈렛", image: `${IMG}/omelette.webp`, tags: ["아침", "점심", "가벼움"] },
  { menu: "도넛", image: `${IMG}/donut.webp`, tags: ["점심", "가벼움"] },
  { menu: "프레첼", image: `${IMG}/pretzel.webp`, tags: ["점심", "저녁"] },
  { menu: "포케 연어포케", image: `${IMG}/poke.webp`, tags: ["점심", "저녁", "혼밥", "다이어트"] },
  { menu: "페퍼로니 피자", image: `${IMG}/pizza.webp`, tags: ["점심", "저녁", "회식", "든든함", "야식"] },
  { menu: "치킨버거", image: `${IMG}/hamburger.webp`, tags: ["점심", "저녁", "회식", "고기", "든든함"] },
  { menu: "클럽 샌드위치", image: `${IMG}/sandwich.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "프렌치 토스트", image: `${IMG}/toast.webp`, tags: ["아침", "점심", "가벼움"] },
  { menu: "치킨 윙 버팔로윙", image: `${IMG}/chicken.webp`, tags: ["점심", "저녁", "회식", "고기", "든든함"] },
  { menu: "시저 샐러드", image: `${IMG}/salmon.webp`, tags: ["점심", "여름", "다이어트", "가벼움"] },
  { menu: "베이글 샌드위치", image: `${IMG}/sandwich.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "미트볼 스테이크", image: `${IMG}/steak.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "맥앤치즈", image: `${IMG}/cheese-sticks.webp`, tags: ["점심", "저녁"] },
  { menu: "브런치 팬케이크", image: `${IMG}/pancake.webp`, tags: ["아침", "점심", "가벼움"] },

];

const china: MenuItem[] = [
  { menu: "짜장면 짬뽕 삼선짜장", image: `${IMG}/jjajangmyun.webp`, tags: ["해장", "저녁", "면", "매움"] },
  { menu: "탕수육", image: `${IMG}/tangsuyook.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "마라탕", image: `${IMG}/malatang.jfif`, tags: ["점심", "저녁", "겨울", "국물", "매움"] },
  { menu: "마라샹궈", image: `${IMG}/mlsg.webp`, tags: ["점심", "저녁", "매움"] },
  { menu: "고추잡채", image: `${IMG}/gcj.webp`, tags: ["점심", "저녁"] },
  { menu: "깐풍기", image: `${IMG}/kpg.jfif`, tags: ["점심", "저녁", "매움"] },
  { menu: "딤섬", image: `${IMG}/dim-sum.webp`, tags: ["점심", "저녁"] },
  { menu: "팔보채", image: `${IMG}/pbc.webp`, tags: ["점심", "저녁"] },
  { menu: "꿔바로우", image: `${IMG}/gbr.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "마파두부", image: `${IMG}/mafatofu.webp`, tags: ["점심", "저녁", "봄", "매움"] },
  { menu: "훠궈 샤브샤브 핫팟", image: `${IMG}/shabu.webp`, tags: ["점심", "저녁", "회식", "겨울", "국물"] },
  { menu: "샤브톡톡 샤브샤브 1인샤브", image: `${IMG}/shabu.webp`, tags: ["점심", "저녁", "회식", "겨울", "국물"] },
  { menu: "북경오리 베이징덕", image: `${IMG}/pekingduck.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "샤오롱바오", image: `${IMG}/xiaolong.webp`, tags: ["점심", "저녁"] },
  { menu: "양장피", image: `${IMG}/pbc.webp`, tags: ["점심", "저녁"] },
  { menu: "유산슬", image: `${IMG}/pbc.webp`, tags: ["점심", "저녁"] },
  { menu: "깐쇼새우", image: `${IMG}/kpg.jfif`, tags: ["점심", "저녁"] },
  { menu: "라조기", image: `${IMG}/kpg.jfif`, tags: ["점심", "저녁"] },
  { menu: "멘보샤", image: `${IMG}/dim-sum.webp`, tags: ["점심", "저녁"] },
  { menu: "탄탄면", image: `${IMG}/malatang.jfif`, tags: ["점심", "저녁", "면", "매움"] },
  { menu: "우육면", image: `${IMG}/jjajangmyun.webp`, tags: ["점심", "저녁", "국물", "면", "고기"] },
  { menu: "동파육", image: `${IMG}/pekingduck.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "볶음밥 계란볶음밥", image: `${IMG}/jjajangmyun.webp`, tags: ["점심", "저녁", "혼밥", "든든함"] },
  { menu: "차오미엔 중국식볶음면", image: `${IMG}/jjajangmyun.webp`, tags: ["점심", "저녁", "혼밥", "면"] },

];

const japan: MenuItem[] = [
  { menu: "라멘", image: `${IMG}/ramen.webp`, tags: ["점심", "저녁", "혼밥", "겨울"] },
  { menu: "덴뿌라", image: `${IMG}/tempura.webp`, tags: ["점심", "저녁"] },
  { menu: "스시 초밥", image: `${IMG}/sushi.webp`, tags: ["점심", "저녁", "혼밥", "가벼움"] },
  { menu: "돈카츠 경양식돈까스", image: `${IMG}/tonkatsu.webp`, tags: ["점심", "저녁", "고기", "든든함"] },
  { menu: "규카츠 소고기카츠 화로구이카츠", image: `${IMG}/tonkatsu.webp`, tags: ["점심", "저녁", "고기", "든든함"] },
  { menu: "야끼도리", image: `${IMG}/yakitori.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "우동 가케우동", image: `${IMG}/udon.webp`, tags: ["점심", "저녁", "혼밥", "겨울"] },
  { menu: "오코노미야키", image: `${IMG}/okonomiyaki.webp`, tags: ["점심", "저녁"] },
  { menu: "타코야키", image: `${IMG}/takoyaki.webp`, tags: ["점심", "저녁", "혼밥", "분식"] },
  { menu: "치라시스시 치라시볼", image: `${IMG}/chirashi.webp`, tags: ["점심", "저녁", "혼밥", "가벼움"] },
  { menu: "스키야키", image: `${IMG}/sukiyaki.webp`, tags: ["점심", "저녁", "겨울", "고기"] },
  { menu: "돈부리", image: `${IMG}/donburi.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "소바", image: `${IMG}/soba.webp`, tags: ["점심", "저녁", "혼밥", "여름"] },
  { menu: "오야코동", image: `${IMG}/oyakodon.webp`, tags: ["점심", "저녁", "혼밥", "고기"] },
  { menu: "오차즈케 녹차밥", image: `${IMG}/och.webp`, tags: ["아침", "저녁", "다이어트", "가벼움"] },
  { menu: "카레라이스 일본식카레", image: `${IMG}/donburi.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "가츠동", image: `${IMG}/tonkatsu.webp`, tags: ["점심", "저녁"] },
  { menu: "텐동", image: `${IMG}/tempura.webp`, tags: ["점심", "저녁"] },
  { menu: "규동", image: `${IMG}/donburi.webp`, tags: ["점심", "저녁"] },
  { menu: "츠케멘", image: `${IMG}/ramen.webp`, tags: ["점심", "저녁"] },
  { menu: "미소시루", image: `${IMG}/udon.webp`, tags: ["점심", "저녁"] },
  { menu: "사시미", image: `${IMG}/sushi.webp`, tags: ["점심", "저녁"] },
  { menu: "이자카야 나베", image: `${IMG}/sukiyaki.webp`, tags: ["점심", "저녁"] },
  { menu: "야키소바", image: `${IMG}/soba.webp`, tags: ["점심", "저녁", "혼밥", "여름"] },
  { menu: "일본식 카레우동", image: `${IMG}/udon.webp`, tags: ["점심", "저녁", "혼밥", "겨울"] },

];

const asia: MenuItem[] = [
  { menu: "쌀국수 Pho", image: `${IMG}/pho.webp`, tags: ["점심", "저녁", "국물", "면"] },
  { menu: "분짜", image: `${IMG}/bunjja.webp`, tags: ["점심", "저녁"] },
  { menu: "팟타이", image: `${IMG}/pod.webp`, tags: ["점심", "저녁", "혼밥", "면"] },
  { menu: "반미샌드위치", image: `${IMG}/banhmi.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "쏨땀 태국샐러드", image: `${IMG}/somtam.webp`, tags: ["점심", "여름", "매움", "다이어트"] },
  { menu: "망고 찹쌀밥", image: `${IMG}/mango.webp`, tags: ["점심", "여름", "가벼움"] },
  { menu: "나시고랭", image: `${IMG}/nasi-goreng.webp`, tags: ["점심", "저녁", "혼밥", "든든함"] },
  { menu: "인도 커리 & 난", image: `${IMG}/indiancurry.webp`, tags: ["점심", "저녁", "혼밥", "겨울"] },
  { menu: "탄두리 치킨", image: `${IMG}/tanduri.webp`, tags: ["점심", "저녁", "회식", "고기", "든든함"] },
  { menu: "양꼬치", image: `${IMG}/yangkkochi.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "똠양꿍", image: `${IMG}/tygtyg.webp`, tags: ["점심", "저녁", "국물", "매움"] },
  { menu: "월남쌈 베트남 스프링롤", image: `${IMG}/vietssam.webp`, tags: ["점심", "저녁", "여름", "다이어트"] },
  { menu: "그린커리 태국커리", image: `${IMG}/indiancurry.webp`, tags: ["점심", "저녁", "혼밥", "겨울"] },
  { menu: "카오팟 태국볶음밥", image: `${IMG}/nasi-goreng.webp`, tags: ["점심", "저녁", "혼밥", "든든함"] },
  { menu: "락사", image: `${IMG}/pho.webp`, tags: ["점심", "저녁", "국물", "면"] },
  { menu: "미고렝", image: `${IMG}/nasi-goreng.webp`, tags: ["점심", "저녁", "혼밥", "면"] },
  { menu: "사테 꼬치", image: `${IMG}/yangkkochi.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "바쿠테", image: `${IMG}/tygtyg.webp`, tags: ["점심", "저녁", "국물", "고기"] },
  { menu: "짜조 베트남튀김롤", image: `${IMG}/vietssam.webp`, tags: ["점심", "저녁", "분식", "가벼움"] },
  { menu: "치킨 비리야니", image: `${IMG}/tanduri.webp`, tags: ["점심", "저녁", "회식", "고기", "든든함"] },
  { menu: "라씨", image: `${IMG}/mango.webp`, tags: ["점심", "저녁"] },
  { menu: "파파야 샐러드", image: `${IMG}/somtam.webp`, tags: ["점심", "여름", "다이어트", "가벼움"] },

];

const mexico: MenuItem[] = [
  { menu: "타코", image: `${IMG}/tacos.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "엔칠라다", image: `${IMG}/enchiladas.webp`, tags: ["점심", "저녁", "매움", "든든함"] },
  { menu: "케사디아", image: `${IMG}/quesadilla.webp`, tags: ["점심", "저녁", "혼밥", "든든함"] },
  { menu: "감바스 알 아히요", image: `${IMG}/gambas.webp`, tags: ["점심", "저녁"] },
  { menu: "타말레스", image: `${IMG}/tamales.webp`, tags: ["점심", "저녁", "든든함"] },
  { menu: "포졸레", image: `${IMG}/pozole.webp`, tags: ["해장", "저녁", "겨울", "국물"] },
  { menu: "파히타", image: `${IMG}/fajitas.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "과카몰리", image: `${IMG}/guacamole.webp`, tags: ["점심", "저녁", "가벼움"] },
  { menu: "빠에야 Paella", image: `${IMG}/paella.webp`, tags: ["점심", "저녁", "든든함"] },
  { menu: "가스파초 Gazpacho", image: `${IMG}/gazpacho.webp`, tags: ["점심", "저녁", "여름", "다이어트"] },
  { menu: "타파스 Tapas", image: `${IMG}/tapas.webp`, tags: ["점심", "저녁", "회식"] },
  { menu: "세비체 Ceviche", image: `${IMG}/ceviche.webp`, tags: ["점심", "저녁", "여름", "다이어트"] },
  { menu: "부리토", image: `${IMG}/tacos.webp`, tags: ["점심", "저녁"] },
  { menu: "나초", image: `${IMG}/guacamole.webp`, tags: ["점심", "저녁"] },
  { menu: "치미창가", image: `${IMG}/quesadilla.webp`, tags: ["점심", "저녁"] },
  { menu: "카르니타스", image: `${IMG}/fajitas.webp`, tags: ["점심", "저녁"] },
  { menu: "엘로테 멕시칸옥수수", image: `${IMG}/tamales.webp`, tags: ["점심", "저녁"] },
  { menu: "칠레 콘 카르네", image: `${IMG}/pozole.webp`, tags: ["점심", "저녁"] },
  { menu: "토스타다", image: `${IMG}/tacos.webp`, tags: ["점심", "저녁"] },
  { menu: "초리소 타코", image: `${IMG}/tacos.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "스페인 오믈렛 토르티야", image: `${IMG}/tapas.webp`, tags: ["아침", "점심", "가벼움"] },
  { menu: "추로스", image: `${IMG}/tamales.webp`, tags: ["점심", "저녁"] },

];

const italy: MenuItem[] = [
  { menu: "라자냐", image: `${IMG}/lasagna.webp`, tags: ["점심", "저녁", "고기", "든든함"] },
  { menu: "카프레제", image: `${IMG}/caprese.webp`, tags: ["점심", "저녁", "봄", "다이어트"] },
  { menu: "젤라또", image: `${IMG}/gelato.webp`, tags: ["점심", "여름", "가벼움"] },
  { menu: "파스타 알리오올리오 봉골레 까르보나라 볼로네제 크림", image: `${IMG}/pasta.webp`, tags: ["점심", "저녁", "혼밥", "면"] },
  { menu: "마르게리따 피자", image: `${IMG}/margherita-pizza.webp`, tags: ["점심", "저녁", "회식", "든든함", "야식"] },
  { menu: "화덕피자 나폴리피자 루꼴라피자", image: `${IMG}/margherita-pizza.webp`, tags: ["점심", "저녁", "회식", "든든함", "야식"] },
  { menu: "리조또", image: `${IMG}/risotto.webp`, tags: ["점심", "저녁", "혼밥", "든든함"] },
  { menu: "브루스케타", image: `${IMG}/bruschetta.webp`, tags: ["점심", "저녁", "봄", "가벼움"] },
  { menu: "티라미수", image: `${IMG}/tiramisu.webp`, tags: ["점심", "저녁", "가벼움"] },
  { menu: "파니니", image: `${IMG}/panini.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "라비올리", image: `${IMG}/lavioli.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "뇨키", image: `${IMG}/lavioli.webp`, tags: ["점심", "저녁"] },
  { menu: "카르보나라", image: `${IMG}/pasta.webp`, tags: ["점심", "저녁"] },
  { menu: "봉골레 파스타", image: `${IMG}/pasta.webp`, tags: ["점심", "저녁", "혼밥", "면"] },
  { menu: "아란치니", image: `${IMG}/risotto.webp`, tags: ["점심", "저녁"] },
  { menu: "미네스트로네 수프", image: `${IMG}/risotto.webp`, tags: ["점심", "저녁", "국물"] },
  { menu: "오소부코", image: `${IMG}/lasagna.webp`, tags: ["점심", "저녁"] },
  { menu: "프로슈토 루꼴라 피자", image: `${IMG}/margherita-pizza.webp`, tags: ["점심", "저녁", "회식", "든든함", "야식"] },
  { menu: "포르치니 리조또", image: `${IMG}/risotto.webp`, tags: ["점심", "저녁", "혼밥", "든든함"] },
  { menu: "카놀리", image: `${IMG}/tiramisu.webp`, tags: ["점심", "저녁"] },
  { menu: "포카치아", image: `${IMG}/bruschetta.webp`, tags: ["점심", "저녁"] },

];

const france: MenuItem[] = [
  { menu: "크로크무슈", image: `${IMG}/croque.webp`, tags: ["아침", "저녁"] },
  { menu: "키쉬 로레인", image: `${IMG}/quiche.webp`, tags: ["점심", "저녁", "봄"] },
  { menu: "니수아즈 샐러드", image: `${IMG}/salade.webp`, tags: ["점심", "여름", "다이어트", "가벼움"] },
  { menu: "라따뚜이", image: `${IMG}/ratatouille.webp`, tags: ["점심", "저녁", "봄", "다이어트"] },
  { menu: "부야베스 해물스튜", image: `${IMG}/bouillabaisse.webp`, tags: ["점심", "저녁", "겨울", "국물"] },
  { menu: "스테이크 감자프라이", image: `${IMG}/steak-frites.webp`, tags: ["점심", "저녁", "회식", "고기"] },
  { menu: "타르트 태탕 사과파이", image: `${IMG}/tarte-tatin.webp`, tags: ["점심", "가을", "가벼움"] },
  { menu: "크레페", image: `${IMG}/crepe.webp`, tags: ["아침", "저녁", "가벼움"] },
  { menu: "그라탕", image: `${IMG}/gratin.webp`, tags: ["점심", "저녁", "겨울", "든든함"] },
  { menu: "에스까르고", image: `${IMG}/escargot.webp`, tags: ["점심", "저녁", "고기"] },
  { menu: "포아그라", image: `${IMG}/foie-Gras.webp`, tags: ["점심", "저녁", "고기"] },
  { menu: "마카롱", image: `${IMG}/macaron.webp`, tags: ["점심", "여름", "가벼움"] },
  { menu: "양파 수프", image: `${IMG}/onionsoup.webp`, tags: ["해장", "저녁", "겨울", "국물"] },
  { menu: "클레멘타인 크럼블", image: `${IMG}/clementine.webp`, tags: ["점심", "저녁"] },
  { menu: "레몬 타르트", image: `${IMG}/tartecit.webp`, tags: ["점심", "가벼움"] },
  { menu: "코코뱅", image: `${IMG}/bouillabaisse.webp`, tags: ["점심", "저녁"] },
  { menu: "뵈프 부르기뇽", image: `${IMG}/steak-frites.webp`, tags: ["점심", "저녁"] },
  { menu: "크렘 브륄레", image: `${IMG}/clementine.webp`, tags: ["점심", "저녁"] },
  { menu: "바게트 샌드위치", image: `${IMG}/croque.webp`, tags: ["점심", "저녁", "혼밥"] },
  { menu: "프렌치 어니언 그라탕", image: `${IMG}/onionsoup.webp`, tags: ["점심", "저녁", "겨울", "국물"] },
  { menu: "홍합찜 물마리니에르", image: `${IMG}/bouillabaisse.webp`, tags: ["점심", "저녁", "든든함"] },
  { menu: "오리 콩피", image: `${IMG}/foie-Gras.webp`, tags: ["점심", "저녁", "고기"] },
  { menu: "샤퀴테리 플래터", image: `${IMG}/foie-Gras.webp`, tags: ["점심", "저녁"] },
  { menu: "수플레", image: `${IMG}/gratin.webp`, tags: ["점심", "저녁"] },
  { menu: "프랑스식 오믈렛", image: `${IMG}/quiche.webp`, tags: ["아침", "점심", "가벼움"] },

];

const menuData: MenuMap = {
  all: [...korea, ...pizza, ...china, ...japan, ...asia, ...mexico, ...italy, ...france],
  korea,
  pizza,
  china,
  japan,
  asia,
  mexico,
  italy,
  france,
};

export default menuData;

export const countryLabels: Record<CountryType, string> = {
  all: '🌍 전체',
  korea: '🇰🇷 한식',
  pizza: '🍕 피자/치킨/양식',
  china: '🇨🇳 중식',
  japan: '🇯🇵 일식',
  asia: '🌏 아시안',
  mexico: '🇲🇽 스페인/멕시코',
  italy: '🇮🇹 이탈리아',
  france: '🇫🇷 프랑스',
};
